<?php
namespace WPDSQLMigration;
/** Generate DSQL schema from inspected MySQL metadata, never execute a SQL dump. */
final class Plan {
    public static function type(array $c): string {
        $t=strtolower($c['Type']);
        if (preg_match('/\b(zerofill|binary)\b/',$t) || preg_match('/(?:VIRTUAL|STORED)\s+GENERATED|on update|INVISIBLE/i',$c['Extra']??'')) { throw new \RuntimeException('Unsupported generated/automatic/binary column behavior'); }
        if (str_contains($c['Extra']??'','auto_increment')) {
            if (!preg_match('/^(tinyint|smallint|mediumint|int|bigint)/',$t)) { throw new \RuntimeException('Unsupported identity type'); }
            return 'bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1)';
        }
        if (preg_match('/^(tinyint|smallint)/',$t)) { return 'integer'; }
        if (preg_match('/^(mediumint|int|bigint)/',$t)) { return 'bigint'; }
        if (preg_match('/^(?:decimal|numeric)\((\d+),(\d+)\)/',$t,$m)) { return 'numeric('.$m[1].','.$m[2].')'; }
        if (preg_match('/^(?:var)?char\((\d+)\)/',$t,$m)) { return 'varchar('.$m[1].')'; }
        if (preg_match('/^(tinytext|mediumtext|longtext|text|enum\()/',$t)) { return 'text'; }
        if (preg_match('/^(datetime|timestamp)/',$t)) { return 'timestamp without time zone'; }
        if ($t==='date') { return 'date'; }
        if ($t==='json') { return 'json'; }
        if (preg_match('/^(tinyblob|mediumblob|longblob|blob|varbinary\()/',$t)) { return 'bytea'; }
        throw new \RuntimeException('Unsupported MySQL type: '.$t);
    }
    public static function temporal(array $c): bool { return (bool)preg_match('/^(datetime|timestamp|date)\b/i',$c['Type']); }
    public static function convert(?string $value,array $c,bool $reverse=false,bool $codec=false): ?string {
        if ($value===null) return null;
        if (!self::temporal($c)) { return $codec ? ($reverse ? \DSQL_Value_Codec::decode($value) : \DSQL_Value_Codec::encode($value)) : $value; }
        if ($reverse) {
            $value=preg_replace('/^0001-01-01/', '0000-00-00', $value);
            if (preg_match('/^(?:datetime|timestamp)\((\d+)\)/i',$c['Type'],$precision)) {
                [$base,$fraction]=array_pad(explode('.',$value,2),2,'');
                $value=$base.'.'.str_pad($fraction,(int)$precision[1],'0');
            }
            return $value;
        }
        return preg_replace('/^0000-00-00/', '0001-01-01', $value);
    }
    public static function indexes(array $t): array {
        $groups=[];
        if ($t['archived']??false) return [];
        foreach ($t['indexes'] as $index) {
            if (in_array($index['Key_name'],$t['omitted_indexes']??[],true)) continue;
            if ($index['Index_type']!=='BTREE' || !empty($index['Expression'])) { throw new \RuntimeException('Unsupported index type/expression'); }
            if (!(int)$index['Non_unique'] && $index['Sub_part']!==null) { throw new \RuntimeException('A unique prefix index needs explicit DSQL emulation'); }
            $groups[$index['Key_name']][(int)$index['Seq_in_index']]=$index;
        }
        foreach ($groups as &$group) { ksort($group);$group=array_values($group); }
        return $groups;
    }
    public static function tableName(array $t): string { return Backup::qi($t['target_schema']??'public').'.'.Backup::qi($t['name']); }
    public static function ddl(array $t,\PDO $pdo): array {
        $fields=[];$groups=self::indexes($t);
        if (preg_match('/\bFOREIGN\s+KEY\b|\bCHECK\s*\(|\bPARTITION\s+BY\b/i',$t['mysql_ddl'])) { throw new \RuntimeException('Explicit constraint/partition translation is required'); }
        foreach ($t['columns'] as $c) {
            $type=self::type($c);$line=Backup::qi($c['Field']).' '.$type;
            if ($c['Null']==='NO') { $line.=' NOT NULL'; }
            if (!str_contains($c['Extra']??'','auto_increment') && $c['Default']!==null) {
                $value=(string)$c['Default'];
                $line.=' DEFAULT '.(preg_match('/^CURRENT_TIMESTAMP(?:\(\d*\))?$/i',$value)&&self::temporal($c) ? 'CURRENT_TIMESTAMP' : $pdo->quote(self::convert($value,$c,false,$t['value_codec']??false)));
            }
            if (str_starts_with(strtolower($c['Type']), 'enum(')) {
                $values=str_getcsv(substr($c['Type'],5,-1),',',"'",'\\');
                $line.=' CHECK ('.Backup::qi($c['Field']).' IN ('.implode(',',array_map([$pdo,'quote'],$values)).'))';
            }
            $fields[]=$line;
        }
        if (isset($groups['PRIMARY'])) { $fields[]='PRIMARY KEY ('.implode(',',array_map(static fn($i)=>Backup::qi($i['Column_name']),$groups['PRIMARY'])).')'; }
        $ddl=['CREATE TABLE '.self::tableName($t).' ('.implode(',',$fields).')'];
        foreach ($groups as $name=>$group) {
            if ($name==='PRIMARY') { continue; }
            $indexName=$t['name'].'_'.$name;
            if (strlen($indexName)>63) { $indexName=substr($indexName,0,46).'_'.substr(hash('sha256',$indexName),0,16); }
            $ddl[]='CREATE '.(!$group[0]['Non_unique']?'UNIQUE ':'').'INDEX ASYNC '.Backup::qi($indexName).' ON '.self::tableName($t).' ('.implode(',',array_map(static fn($i)=>Backup::qi($i['Column_name']),$group)).')';
        }
        return $ddl;
    }
    /** Validate the complete backup before mutating an empty destination. */
    public static function inspect(string $directory,array $manifest): array {
        $issues=[];$rows=0;
        foreach ($manifest['tables'] as $t) {
            $label=$t['name'];$columns=$t['columns'];$hashes=[];$count=0;
            try {
                if (strlen($label)>63 || count($columns)>255) { throw new \RuntimeException('DSQL identifier/column limit'); }
                if (preg_match('/\bFOREIGN\s+KEY\b|\bCHECK\s*\(|\bPARTITION\s+BY\b/i',$t['mysql_ddl'])) { throw new \RuntimeException('Explicit constraint/partition translation is required'); }
                foreach ($columns as $c) {if (strlen($c['Field'])>63) throw new \RuntimeException('A column identifier exceeds the PostgreSQL 63-byte limit');}
                $types=[];foreach ($columns as $c) { $types[]=self::type($c); }
                $groups=self::indexes($t);
                if (count($groups)>25) { throw new \RuntimeException('DSQL index limit'); }
                foreach ($groups as $g) { if (count($g)>8) throw new \RuntimeException('DSQL index-column limit'); }
                foreach (Backup::rows($directory,$t) as $row) {
                    $hashes[]=hash('sha256',Backup::row($row));$count++;$bytes=0;
                    foreach ($row as $i=>$value) {
                        if ($value===null) { continue; }
                        $stored=$types[$i]==='bytea'?$value:self::convert($value,$columns[$i],false,$t['value_codec']??false);
                        $bytes+=strlen($stored);
                        if (strlen($stored)>1048576) { throw new \RuntimeException('A column exceeds DSQL 1 MiB limit after encoding'); }
                        if ($types[$i]!=='bytea' && (!preg_match('//u',$value) || str_contains($stored,"\0"))) { throw new \RuntimeException('A text value is not PostgreSQL-compatible UTF-8'); }
                        if (str_contains($value,"\0") && $types[$i]!=='bytea') {
                            if ($types[$i]!=='text') throw new \RuntimeException('NUL text codec requires a TEXT column');
                            foreach($groups as $g) foreach($g as $part) if($part['Column_name']===$columns[$i]['Field']) throw new \RuntimeException('NUL encoding of indexed text is unsupported');
                        }
                        if (preg_match('/^varchar\((\d+)\)$/',$types[$i],$size) && mb_strlen($stored,'UTF-8')>(int)$size[1]) throw new \RuntimeException('Encoded value exceeds original varchar capacity');
                        if (self::temporal($columns[$i]) && str_starts_with($value,'0001-01-01')) { throw new \RuntimeException('Reserved zero-date sentinel occurs in a source date'); }
                        if (str_starts_with($types[$i],'bigint') && preg_match('/^\d{19,}$/',$value) && (strlen($value)>19 || strcmp($value,'9223372036854775807')>0)) { throw new \RuntimeException('Integer exceeds signed PostgreSQL bigint range'); }
                    }
                    if ($bytes>2*1048576) { throw new \RuntimeException('A row exceeds DSQL 2 MiB limit'); }
                    foreach ($groups as $g) {
                        $keyBytes=0;
                        foreach ($g as $part) { $pos=array_search($part['Column_name'],array_column($columns,'Field'),true);if ($pos===false) throw new \RuntimeException('Unknown indexed column');$keyBytes+=strlen($row[$pos]??''); }
                        if ($keyBytes>900) { throw new \RuntimeException('An index key needs review against the DSQL 1 KiB encoded-key limit'); }
                    }
                }
                if ($count!==$t['rows'] || !hash_equals($t['rows_sha256'],Backup::digest($hashes))) { throw new \RuntimeException('Row count/digest mismatch'); }
            } catch (\Throwable $e) { $issues[]=['table'=>$label,'reason'=>$e->getMessage()]; }
            $rows+=$count;
        }
        return ['format'=>'wordpress-dsql-restore-plan-v1','tables'=>count($manifest['tables']),'rows'=>$rows,'archive_tables'=>count(array_filter($manifest['tables'],static fn($t)=>$t['archived']??false)),'policy_sha256'=>$manifest['policy_sha256']??null,'restore_supported'=>!$issues,'issues'=>$issues,'cutover_ready'=>false,'cutover_note'=>'Requires a write freeze, a final verified snapshot, full application checks, and an explicit cutover decision.'];
    }
}
