<?php
require dirname(__DIR__,2).'/vendor/autoload.php';
use WPDSQL\Engine\{Config,Driver};
use WPDSQL\MySQL\Translation\Renderer;
$root=dirname(__DIR__,2);$cluster=json_decode(file_get_contents($root.'/.local/cluster.json'),true);$s=json_decode(file_get_contents($root.'/.local/settings.json'),true);
if(($cluster['tags']['Purpose']??'')!=='synthetic-wordpress-compatibility'||$s['endpoint']!==$cluster['identifier'].'.dsql.'.$s['region'].'.on.aws')throw new RuntimeException('Synthetic cluster only');
$d=new Driver(new Config(host:$s['endpoint'],region:$s['region'],profile:$s['profile'],tablePrefix:'perfmeta_'));
if($d->isConnected())throw new RuntimeException('Construction opened connection');
$d->checkConnection();$p=(new ReflectionProperty($d,'pdo'))->getValue($d);$name='perfmeta_physical';
try{
 $p->exec('CREATE TABLE '.$name.' (id bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY, a smallint, b integer NOT NULL, c bigint, d real, e double precision, f numeric(12,2), g varchar(80), h text, i timestamp, j date, k bytea, l boolean, m json, dropped text)');
 $compare=function()use($p,$name){
  $q=$p->prepare('SELECT column_name,data_type,is_nullable,is_identity FROM information_schema.columns WHERE table_schema=? AND table_name=? ORDER BY ordinal_position');$q->execute(['public',$name]);$expected=$q->fetchAll(PDO::FETCH_ASSOC);
  $actual=(new ReflectionMethod(Renderer::class,'metadata'))->invoke(new Renderer($p,'public',false),$name);
  if(array_values($actual)!==$expected)throw new RuntimeException('Physical metadata field mismatch');
 };
 $compare();$p->exec('ALTER TABLE '.$name.' DROP COLUMN dropped');$compare();
 $missing=(new ReflectionMethod(Renderer::class,'metadata'))->invoke(new Renderer($p,'public',false),'perfmeta_missing');if($missing!==[])throw new RuntimeException('Missing table lookup changed');
 echo "PASS physical types, nullability, identities, dropped columns and missing tables\n";
}finally{$p->exec('DROP TABLE IF EXISTS '.$name);$d->close();}
