<?php
require __DIR__.'/bootstrap.php';
require $root.'/vendor/autoload.php';
$s=lab();
// Live tag check must precede all fixture writes, including cleanup.
$command=['aws','dsql','get-cluster','--identifier',explode('.',$s['endpoint'])[0],'--region',$s['region'],'--profile',$s['profile'],'--output','json'];
$p=proc_open($command,[1=>['pipe','w'],2=>['pipe','w']],$pipes);
$live=json_decode(stream_get_contents($pipes[1]),true);fclose($pipes[1]);fclose($pipes[2]);
if(proc_close($p)!==0||($live['tags']['Purpose']??'')!=='synthetic-wordpress-compatibility')throw new RuntimeException('Live synthetic lab tag required');
$pdo=WPDSQL\Engine\AwsConnection::connect(new WPDSQL\Engine\Config(host:$s['endpoint'],region:$s['region'],profile:$s['profile']));
if(($argv[1]??'')==='cleanup'){
    $f=fixture();foreach(['meta','posts'] as $key){$t=$f[$key];if(!preg_match('/^native_poc_[0-9a-f]{8}_(posts|meta)$/D',$t))throw new RuntimeException('Invalid fixture name');$pdo->exec('DROP TABLE IF EXISTS "'.$t.'"');}
    unlink($root.'/.local/native-fixture.json');echo "Synthetic fixture removed\n";exit;
}
if(file_exists($root.'/.local/native-fixture.json'))throw new RuntimeException('Existing fixture: clean it up explicitly first');
$prefix='native_poc_'.bin2hex(random_bytes(4)).'_';$t=$prefix.'posts';$m=$prefix.'meta';
$f=['prefix'=>$prefix,'posts'=>$t,'meta'=>$m,'revision'=>bin2hex(random_bytes(8))];
file_put_contents($root.'/.local/native-fixture.json',json_encode($f));chmod($root.'/.local/native-fixture.json',0600);
$pdo->exec('CREATE TABLE "'.$t.'" ("ID" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1001 CACHE 1) PRIMARY KEY,post_title text,post_status varchar(20) NOT NULL,stamp timestamp NOT NULL)');
$pdo->exec('CREATE TABLE "'.$m.'" (meta_id bigint PRIMARY KEY,post_id bigint NOT NULL,meta_key varchar(50) NOT NULL,meta_value text)');
$pdo->beginTransaction();
for($i=1;$i<=40;$i++){
    $q=$pdo->prepare('INSERT INTO "'.$t.'" ("ID",post_title,post_status,stamp) VALUES (?,?,?,?)');$q->execute([$i,'Synthetic story '.$i,$i%3===0?'draft':'publish','2026-09-19 12:00:00']);
    $q=$pdo->prepare('INSERT INTO "'.$m.'" VALUES (?,?,?,?)');$q->execute([$i,$i,'rating',(string)($i%5)]);
}
$pdo->commit();
echo "Created 80 synthetic rows in two isolated tables\n";
