//! Installation DDL only. Restored/managed schemas retain the guarded upgrade boundary.
use crate::{
    catalog::{self, cell},
    catalog_model as model,
    compiler::{Result, Shape, check, name, qi},
    engine::{Client, Output},
};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use sqlparser::{ast::*, dialect::MySqlDialect, parser::Parser};
use std::{
    collections::{BTreeMap, BTreeSet},
    sync::OnceLock,
};
pub fn is_ddl(s: &Statement) -> bool {
    matches!(
        s,
        Statement::CreateTable(_)
            | Statement::AlterTable { .. }
            | Statement::Drop { .. }
            | Statement::Truncate { .. }
            | Statement::CreateIndex(_)
    ) || s.to_string().starts_with("RENAME TABLE")
}
fn pg_literal(s: &str) -> String {
    format!("E'{}'", s.replace('\\', "\\\\").replace('\'', "''"))
}
fn literal(e: &Expr, shape: &Shape) -> Result<(Option<String>, bool)> {
    if let Some(i) = crate::compiler::Compiler::slot(e) {
        return Ok((Some(shape.values[i].clone()), false));
    }
    match e {
        Expr::Value(v) if matches!(v.value, sqlparser::ast::Value::Null) => Ok((None, false)),
        Expr::Value(v) if matches!(v.value, sqlparser::ast::Value::Boolean(_)) => Ok((
            Some(
                if v.value == sqlparser::ast::Value::Boolean(true) {
                    "1"
                } else {
                    "0"
                }
                .into(),
            ),
            false,
        )),
        Expr::UnaryOp {
            op: UnaryOperator::Minus,
            expr,
        } => {
            let (v, expression) = literal(expr, shape)?;
            check(!expression)?;
            Ok((v.map(|v| format!("-{v}")), false))
        }
        Expr::Function(f) if f.name.to_string().eq_ignore_ascii_case("CURRENT_TIMESTAMP") => {
            check(f.filter.is_none() && f.over.is_none() && f.within_group.is_empty())?;
            let precision = match &f.args {
                FunctionArguments::None => String::new(),
                FunctionArguments::List(a) if a.args.is_empty() => String::new(),
                FunctionArguments::List(a) if a.args.len() == 1 => {
                    let value = match &a.args[0] {
                        FunctionArg::Unnamed(FunctionArgExpr::Expr(e)) => {
                            literal(e, shape)?.0.ok_or("Precision required")?
                        }
                        _ => return Err("Invalid timestamp precision".into()),
                    };
                    check(
                        value.len() == 1
                            && value.as_bytes()[0].is_ascii_digit()
                            && value.parse::<u8>().unwrap() <= 6,
                    )?;
                    format!("({value})")
                }
                _ => return Err("Invalid timestamp default".into()),
            };
            Ok((Some(format!("CURRENT_TIMESTAMP{precision}")), true))
        }
        _ => Err("Unsupported default expression requires a dedicated migration".into()),
    }
}
fn option_text(e: &Expr, s: &Shape) -> Result<String> {
    match e {
        Expr::Identifier(i) => Ok(i.value.clone()),
        _ => literal(e, s)?.0.ok_or("Option value required".into()),
    }
}
pub fn physical_type(c: &Value) -> Result<String> {
    let t = c["Type"].as_str().ok_or("Missing column type")?;
    if c["Extra"].as_str().unwrap_or("").contains("auto_increment") {
        check(
            ["tinyint", "smallint", "mediumint", "int", "bigint"]
                .iter()
                .any(|p| t.starts_with(p)),
        )?;
        return Ok("bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1)".into());
    }
    Ok(if t.starts_with("tinyint") || t.starts_with("smallint") {
        "integer".into()
    } else if ["mediumint", "int", "bigint"]
        .iter()
        .any(|p| t.starts_with(p))
    {
        "bigint".into()
    } else if t.starts_with("decimal(") || t.starts_with("numeric(") {
        format!("numeric{}", &t[t.find('(').unwrap()..=t.find(')').unwrap()])
    } else if t.starts_with("char(") || t.starts_with("varchar(") {
        format!("varchar{}", &t[t.find('(').unwrap()..=t.find(')').unwrap()])
    } else if t.ends_with("text") {
        "text".into()
    } else if t.starts_with("datetime") || t.starts_with("timestamp") {
        "timestamp without time zone".into()
    } else if t == "date" {
        "date".into()
    } else if t == "json" {
        "json".into()
    } else if t.ends_with("blob") || t.starts_with("varbinary(") {
        "bytea".into()
    } else {
        return Err("Unsupported MySQL column type".into());
    })
}
fn index_rows(
    table: &str,
    key: &str,
    columns: Vec<(String, Option<u64>)>,
    unique: bool,
    comment: &str,
) -> Vec<Value> {
    columns.into_iter().enumerate().map(|(i,(column,prefix))|json!({"Table":table,"Non_unique":if unique{0}else{1},"Key_name":key,"Seq_in_index":i+1,"Column_name":column,"Collation":"A","Cardinality":null,"Sub_part":prefix,"Packed":null,"Null":"","Index_type":"BTREE","Comment":"","Index_comment":comment,"Visible":"YES","Expression":null})).collect()
}
fn index_columns(columns: &[IndexColumn], shape: &Shape) -> Result<Vec<(String, Option<u64>)>> {
    check(!columns.is_empty() && columns.len() <= 8)?;
    let mut out = vec![];
    for column in columns {
        check(
            column.operator_class.is_none()
                && column.column.with_fill.is_none()
                && column.column.options.nulls_first.is_none()
                && matches!(column.column.options.sort, None | Some(OrderBySort::Asc)),
        )?;
        match &column.column.expr {
            Expr::Identifier(i) => out.push((i.value.clone(), None)),
            Expr::Function(f) => {
                let name = name(&f.name)?;
                check(f.filter.is_none() && f.over.is_none() && f.within_group.is_empty())?;
                let a = match &f.args {
                    FunctionArguments::List(a)
                        if a.args.len() == 1
                            && a.clauses.is_empty()
                            && a.duplicate_treatment.is_none() =>
                    {
                        a
                    }
                    _ => return Err("Expression indexes require explicit support".into()),
                };
                let value = match &a.args[0] {
                    FunctionArg::Unnamed(FunctionArgExpr::Expr(e)) => {
                        literal(e, shape)?.0.ok_or("Index prefix required")?
                    }
                    _ => return Err("Invalid index prefix".into()),
                };
                let prefix = value.parse::<u64>().map_err(|_| "Invalid index prefix")?;
                check(prefix > 0)?;
                out.push((name, Some(prefix)));
            }
            _ => return Err("Expression indexes require explicit support".into()),
        }
    }
    Ok(out)
}
fn index_comment(options: &[IndexOption]) -> Result<String> {
    let mut comment = String::new();
    for o in options {
        match o {
            IndexOption::Comment(c) => comment = c.clone(),
            _ => return Err("Unsupported index option".into()),
        }
    }
    Ok(comment)
}
pub fn create_model(
    c: &CreateTable,
    shape: &Shape,
    prefix: &str,
    schema: &str,
    codec: bool,
) -> Result<Value> {
    static BASE: OnceLock<CreateTable> = OnceLock::new();
    let base = BASE.get_or_init(|| {
        match Parser::parse_sql(&MySqlDialect {}, "CREATE TABLE _native_baseline (id int)")
            .unwrap()
            .remove(0)
        {
            Statement::CreateTable(c) => c,
            _ => unreachable!(),
        }
    });
    let mut rest = c.clone();
    rest.name = base.name.clone();
    rest.columns = base.columns.clone();
    rest.constraints.clear();
    rest.if_not_exists = false;
    rest.table_options = base.table_options.clone();
    rest.comment = base.comment.clone();
    check(&rest == base)?;
    let table = name(&c.name)?;
    check(
        table.starts_with(prefix)
            && !table.starts_with("__")
            && table.len() <= 63
            && !c.columns.is_empty(),
    )?;
    let mut options = json!({"engine":"InnoDB","charset":"utf8mb4","collation":null,"comment":""});
    if let Some(CommentDef::WithEq(s) | CommentDef::WithoutEq(s)) = &c.comment {
        options["comment"] = json!(s);
    }
    let table_options = match &c.table_options {
        CreateTableOptions::None => &[][..],
        CreateTableOptions::Plain(o) => o.as_slice(),
        _ => return Err("Unsupported table options".into()),
    };
    for o in table_options {
        match o {
            SqlOption::NamedParenthesizedList(o)
                if o.key.value.eq_ignore_ascii_case("ENGINE") && o.values.is_empty() =>
            {
                let engine = o.name.as_ref().ok_or("Engine required")?.value.clone();
                check(engine.eq_ignore_ascii_case("InnoDB"))?;
                options["engine"] = json!(engine);
            }
            SqlOption::KeyValue { key, value } => {
                let value = option_text(value, shape)?;
                match key.value.to_ascii_uppercase().as_str() {
                    "ENGINE" => {
                        check(value.eq_ignore_ascii_case("InnoDB"))?;
                        options["engine"] = json!(value);
                    }
                    "DEFAULT CHARSET" | "CHARSET" | "DEFAULT CHARACTER SET" | "CHARACTER SET" => {
                        check(value.eq_ignore_ascii_case("utf8mb4"))?;
                        options["charset"] = json!(value);
                    }
                    "COLLATE" | "DEFAULT COLLATE" => {
                        check(
                            value
                                .bytes()
                                .all(|b| b.is_ascii_alphanumeric() || b == b'_'),
                        )?;
                        options["collation"] = json!(value);
                    }
                    _ => return Err("Unsupported table option".into()),
                }
            }
            SqlOption::Comment(CommentDef::WithEq(s) | CommentDef::WithoutEq(s)) => {
                options["comment"] = json!(s)
            }
            _ => return Err("Unsupported table option".into()),
        }
    }
    let types=regex::Regex::new(r"^(?:(?:tinyint|smallint|mediumint|int|integer|bigint)(?:\([0-9]+\))?(?: unsigned)?|(?:decimal|numeric)\([0-9]+,[0-9]+\)(?: unsigned)?|(?:var)?char\([0-9]+\)|(?:tiny|medium|long)?(?:text|blob)|varbinary\([0-9]+\)|(?:datetime|timestamp)(?:\([0-6]\))?|date|json)$").unwrap();
    let mut columns = vec![];
    let mut indexes = vec![];
    let mut names = BTreeSet::new();
    let mut key_names = BTreeSet::new();
    let append = |indexes: &mut Vec<Value>,
                  key_names: &mut BTreeSet<String>,
                  rows: Vec<Value>|
     -> Result<()> {
        let key = rows[0]["Key_name"].as_str().unwrap().to_ascii_lowercase();
        check(key_names.insert(key))?;
        indexes.extend(rows);
        Ok(())
    };
    for col in &c.columns {
        check(names.insert(col.name.value.to_ascii_lowercase()) && col.name.value.len() <= 63)?;
        let ty = col
            .data_type
            .to_string()
            .to_ascii_lowercase()
            .replace(", ", ",");
        check(types.is_match(&ty))?;
        let mut column = json!({"Field":col.name.value,"Type":ty,"Collation":null,"Null":"YES","Key":"","Default":null,"Extra":"","Privileges":"select,insert,update,references","Comment":"","HasDefault":false,"DefaultExpression":false});
        for option in &col.options {
            check(option.name.is_none())?;
            match &option.option {
                ColumnOption::Null => column["Null"] = json!("YES"),
                ColumnOption::NotNull => column["Null"] = json!("NO"),
                ColumnOption::Default(e) => {
                    let (value, expression) = literal(e, shape)?;
                    column["Default"] = json!(value);
                    column["HasDefault"] = json!(true);
                    column["DefaultExpression"] = json!(expression);
                }
                ColumnOption::DialectSpecific(tokens)
                    if tokens
                        .iter()
                        .map(ToString::to_string)
                        .collect::<Vec<_>>()
                        .join(" ")
                        .eq_ignore_ascii_case("AUTO_INCREMENT") =>
                {
                    column["Extra"] = json!("auto_increment");
                    column["Null"] = json!("NO");
                }
                ColumnOption::PrimaryKey(k) => {
                    check(
                        k.name.is_none()
                            && k.index_name.is_none()
                            && k.index_type.is_none()
                            && k.columns.is_empty()
                            && k.include.is_empty()
                            && k.index_options.is_empty()
                            && k.characteristics.is_none(),
                    )?;
                    column["Null"] = json!("NO");
                    append(
                        &mut indexes,
                        &mut key_names,
                        index_rows(
                            &table,
                            "PRIMARY",
                            vec![(col.name.value.clone(), None)],
                            true,
                            "",
                        ),
                    )?;
                }
                ColumnOption::Unique(k) => {
                    check(
                        k.name.is_none()
                            && k.index_name.is_none()
                            && k.index_type.is_none()
                            && k.columns.is_empty()
                            && k.include.is_empty()
                            && k.index_options.is_empty()
                            && k.characteristics.is_none()
                            && k.nulls_distinct == NullsDistinctOption::None,
                    )?;
                    append(
                        &mut indexes,
                        &mut key_names,
                        index_rows(
                            &table,
                            &col.name.value,
                            vec![(col.name.value.clone(), None)],
                            true,
                            "",
                        ),
                    )?;
                }
                ColumnOption::CharacterSet(n) => check(name(n)?.eq_ignore_ascii_case("utf8mb4"))?,
                ColumnOption::Collation(n) => column["Collation"] = json!(name(n)?),
                ColumnOption::Comment(s) => column["Comment"] = json!(s),
                _ => return Err("Unsupported column attribute".into()),
            }
        }
        let physical = physical_type(&column)?;
        if column["DefaultExpression"] == true {
            check(physical.starts_with("timestamp") || physical == "date")?;
        }
        if physical == "bytea" {
            check(column["Default"].is_null())?;
        }
        columns.push(column);
    }
    for constraint in &c.constraints {
        let (key, cols, unique, comment) = match constraint {
            TableConstraint::PrimaryKey(k) => {
                check(
                    k.name.is_none()
                        && k.index_type.is_none()
                        && k.include.is_empty()
                        && k.characteristics.is_none(),
                )?;
                (
                    "PRIMARY".into(),
                    index_columns(&k.columns, shape)?,
                    true,
                    index_comment(&k.index_options)?,
                )
            }
            TableConstraint::Unique(k) => {
                check(
                    k.name.is_none()
                        && k.index_type.is_none()
                        && k.include.is_empty()
                        && k.characteristics.is_none()
                        && k.nulls_distinct == NullsDistinctOption::None,
                )?;
                let cols = index_columns(&k.columns, shape)?;
                (
                    k.index_name
                        .as_ref()
                        .map(|n| n.value.clone())
                        .unwrap_or_else(|| cols[0].0.clone()),
                    cols,
                    true,
                    index_comment(&k.index_options)?,
                )
            }
            TableConstraint::Index(k) => {
                check(k.index_type.is_none())?;
                let cols = index_columns(&k.columns, shape)?;
                (
                    k.name
                        .as_ref()
                        .map(|n| n.value.clone())
                        .unwrap_or_else(|| cols[0].0.clone()),
                    cols,
                    false,
                    index_comment(&k.index_options)?,
                )
            }
            _ => return Err("Unsupported constraint or index type".into()),
        };
        check(cols.iter().all(|(name, prefix)| {
            names.contains(&name.to_ascii_lowercase()) && (!unique || prefix.is_none())
        }))?;
        append(
            &mut indexes,
            &mut key_names,
            index_rows(&table, &key, cols, unique, &comment),
        )?;
    }
    check(key_names.len() <= 25)?;
    let mut model = model::normalized(
        json!({"name":table,"schema_version":2,"columns":columns,"indexes":indexes,"table_options":options,"target_schema":schema,"archived":false,"omitted_indexes":[],"value_codec":codec,"mysql_ddl":""}),
    )?;
    model["source_indexes"] = model["indexes"].clone();
    model["mysql_ddl"] = json!(model::mysql(&model)?);
    Ok(model)
}
fn statements(table: &Value) -> Result<Vec<String>> {
    let target = format!(
        "{}.{}",
        qi(table["target_schema"].as_str().unwrap()),
        qi(table["name"].as_str().unwrap())
    );
    let mut columns = vec![];
    for c in table["columns"].as_array().unwrap() {
        let ty = physical_type(c)?;
        let mut sql = format!("{} {ty}", qi(c["Field"].as_str().unwrap()));
        if c["Null"] == "NO" {
            sql.push_str(" NOT NULL");
        }
        if !c["Default"].is_null() && !c["Extra"].as_str().unwrap_or("").contains("auto_increment")
        {
            let mut value = crate::catalog_expr::string(&c["Default"]).unwrap();
            let temporal = ty == "date" || ty.starts_with("timestamp");
            let default = if c["DefaultExpression"] == true && temporal {
                "CURRENT_TIMESTAMP".into()
            } else {
                if temporal && value.starts_with("0000-00-00") {
                    value.replace_range(..10, "0001-01-01");
                } else if table["value_codec"] == true {
                    value = crate::value::encode(&value);
                }
                pg_literal(&value)
            };
            sql.push_str(&format!(" DEFAULT {default}"));
        }
        columns.push(sql);
    }
    let mut groups: BTreeMap<String, Vec<&Value>> = BTreeMap::new();
    for i in table["indexes"].as_array().unwrap() {
        groups
            .entry(i["Key_name"].as_str().unwrap().into())
            .or_default()
            .push(i);
    }
    if let Some(primary) = groups.remove("PRIMARY") {
        columns.push(format!(
            "PRIMARY KEY ({})",
            primary
                .iter()
                .map(|i| qi(i["Column_name"].as_str().unwrap()))
                .collect::<Vec<_>>()
                .join(",")
        ));
    }
    let mut sql = vec![format!("CREATE TABLE {target} ({})", columns.join(","))];
    for (name, group) in groups {
        let mut physical = format!("{}_{}", table["name"].as_str().unwrap(), name);
        if physical.len() > 63 {
            let digest = format!("{:x}", Sha256::digest(physical.as_bytes()));
            let mut end = 46;
            while !physical.is_char_boundary(end) {
                end -= 1;
            }
            physical = format!("{}_{}", &physical[..end], &digest[..16]);
        }
        sql.push(format!(
            "CREATE {}INDEX ASYNC {} ON {target} ({})",
            if group[0]["Non_unique"] == 0 {
                "UNIQUE "
            } else {
                ""
            },
            qi(&physical),
            group
                .iter()
                .map(|i| qi(i["Column_name"].as_str().unwrap()))
                .collect::<Vec<_>>()
                .join(",")
        ));
    }
    Ok(sql)
}
pub fn execute(client: &mut Client, shape: &Shape) -> Result<Option<Output>> {
    if !is_ddl(&shape.statement) {
        return Ok(None);
    }
    if client.catalog.as_ref().unwrap().managed {
        return Err(
            "Schema changes on restored tables require the controlled DSQL upgrade runner".into(),
        );
    }
    check(!client.in_transaction())?;
    let result = execute_inner(client, shape);
    client.invalidate_schema()?;
    result.map(Some)
}
fn execute_inner(client: &mut Client, shape: &Shape) -> Result<Output> {
    let catalog_name = format!("{}.{}", qi(&client.config.schema), qi("__wp_dsql_schema"));
    match &shape.statement {
        Statement::CreateTable(c) => {
            let table = create_model(
                c,
                shape,
                &client.config.prefix,
                &client.config.schema,
                client.config.value_codec,
            )?;
            let name = table["name"].as_str().unwrap();
            let sql = statements(&table)?;
            let target = format!("{}.{}", qi(&client.config.schema), qi(name));
            let exists = catalog::rows(
                client.raw("SELECT to_regclass($1)::text AS name".into(), vec![target])?,
            )?
            .first()
            .and_then(|r| cell(r, "name"))
            .is_some();
            if exists {
                if c.if_not_exists {
                    return Ok(Output::command("CREATE"));
                }
                return Err("DSQL operation failed (42P07); table already exists".into());
            }
            if !client.catalog.as_ref().unwrap().present {
                client.raw(format!("CREATE TABLE {catalog_name} (table_name text PRIMARY KEY,metadata text NOT NULL,fingerprint text NOT NULL)"),vec![])?;
                client.raw(
                    format!("INSERT INTO {catalog_name} VALUES ($1,$2,$3)"),
                    vec![
                        "__catalog__".into(),
                        "{\"schema_version\":2,\"managed\":false}".into(),
                        "control".into(),
                    ],
                )?;
            }
            let mut pending = table.clone();
            pending["state"] = json!("pending");
            client.raw(
                format!(
                    "INSERT INTO {catalog_name} (table_name,metadata,fingerprint) VALUES ($1,$2,$3)"
                ),
                vec![name.into(), pending.to_string(), "pending".into()],
            )?;
            for statement in sql {
                let index = statement.starts_with("CREATE UNIQUE INDEX")
                    || statement.starts_with("CREATE INDEX");
                let out = client.raw(statement, vec![])?;
                client.queries += 1;
                if index {
                    let job = out
                        .rows
                        .first()
                        .and_then(|r| r.values().next())
                        .and_then(|v| v.as_ref())
                        .and_then(|s| std::str::from_utf8(s).ok())
                        .ok_or("DSQL index job missing")?
                        .to_string();
                    let status = client.raw("CALL sys.wait_for_job($1)".into(), vec![job])?;
                    let ready = status
                        .rows
                        .first()
                        .and_then(|r| r.values().next())
                        .and_then(|v| v.as_ref())
                        .is_some_and(|v| v == b"1" || v == b"t" || v == b"true");
                    if !ready {
                        return Err("DSQL index build failed".into());
                    }
                }
            }
            let fingerprint = client.fingerprint(name, &client.config.schema.clone())?;
            let out = client.raw(
                format!("UPDATE {catalog_name} SET metadata=$1,fingerprint=$2 WHERE table_name=$3"),
                vec![table.to_string(), fingerprint, name.into()],
            )?;
            check(out.affected == 1)?;
            Ok(Output::command("CREATE"))
        }
        Statement::Drop {
            object_type,
            names,
            if_exists,
            cascade,
            restrict,
            purge,
            temporary,
            table,
        } => {
            check(
                *object_type == ObjectType::Table
                    && names.len() == 1
                    && !*cascade
                    && !*restrict
                    && !*purge
                    && !*temporary
                    && table.is_none(),
            )?;
            let name = name(&names[0])?;
            check(name.starts_with(&client.config.prefix) && !name.starts_with("__"))?;
            client.raw(
                format!(
                    "DROP TABLE {}{}.{}",
                    if *if_exists { "IF EXISTS " } else { "" },
                    qi(&client.config.schema),
                    qi(&name)
                ),
                vec![],
            )?;
            client.queries += 1;
            if client.catalog.as_ref().unwrap().present {
                client.raw(
                    format!("DELETE FROM {catalog_name} WHERE table_name=$1"),
                    vec![name],
                )?;
            }
            Ok(Output::command("DROP"))
        }
        _ => Err("Schema alteration requires the controlled upgrade runner".into()),
    }
}
