<?php
/** Synthetic instantiations of WordPress 7.1 source templates, not captured user queries. */
return [
    'search' => ['wp-includes/class-wp-query.php:1450', "SELECT ID FROM wp_posts WHERE (post_title LIKE '%hotel%' OR post_excerpt LIKE '%hotel%' OR post_content LIKE '%hotel%') AND post_password = ''"],
    'calendar_year_month' => ['wp-includes/class-wp-date-query.php:754', 'SELECT ID FROM wp_posts WHERE YEAR(post_date) = 2026 AND MONTH(post_date) = 9'],
    'calendar_week_sunday' => ['wp-includes/functions.php:7194', 'SELECT ID FROM wp_posts WHERE WEEK(post_date, 0) = 36'],
    'calendar_week_monday' => ['wp-includes/functions.php:7185', 'SELECT ID FROM wp_posts WHERE WEEK(post_date, 1) = 36'],
    'calendar_day_of_year' => ['wp-includes/class-wp-date-query.php:757', 'SELECT ID FROM wp_posts WHERE DAYOFYEAR(post_date) = 251'],
    'calendar_day_of_week' => ['wp-includes/class-wp-date-query.php:759', 'SELECT ID FROM wp_posts WHERE DAYOFWEEK(post_date) = 3'],
    'calendar_iso_weekday' => ['wp-includes/class-wp-date-query.php:760', 'SELECT ID FROM wp_posts WHERE WEEKDAY(post_date) + 1 = 2'],
    'calendar_hour_minute' => ['wp-includes/class-wp-date-query.php:1057', "SELECT ID FROM wp_posts WHERE DATE_FORMAT(post_date, '%H.%i') = 10.30"],
    'meta_signed' => ['wp-includes/class-wp-meta-query.php:780', "SELECT post_id FROM wp_postmeta WHERE CAST(meta_value AS SIGNED) >= '10'"],
    'meta_decimal' => ['wp-includes/class-wp-meta-query.php:780', "SELECT post_id FROM wp_postmeta WHERE CAST(meta_value AS DECIMAL(10,2)) >= '10.50'"],
    'meta_binary' => ['wp-includes/class-wp-meta-query.php:780', "SELECT post_id FROM wp_postmeta WHERE CAST(meta_value AS BINARY) = 'Hotel'"],
    'meta_regexp_binary' => ['wp-includes/class-wp-meta-query.php:686', "SELECT post_id FROM wp_postmeta WHERE CAST(meta_key AS BINARY) REGEXP BINARY '^Hotel'"],
    'meta_regexp' => ['wp-includes/class-wp-meta-query.php:681', "SELECT post_id FROM wp_postmeta WHERE meta_key REGEXP '^hotel'"],
    'xmlrpc_rlike' => ['wp-includes/class-wp-xmlrpc-server.php:7008', "SELECT ID FROM wp_posts WHERE post_title RLIKE 'hotel'"],
    'user_not_regexp' => ['wp-includes/user.php:3773', "SELECT user_id FROM wp_usermeta WHERE meta_key = 'wp_capabilities' AND meta_value NOT REGEXP 'administrator'"],
    'site_health_cache_threshold' => ['wp-admin/includes/class-wp-site-health.php:3811', "SELECT TABLE_NAME AS 'table', TABLE_ROWS AS 'rows', SUM(data_length + index_length) as 'bytes' FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'postgres' AND TABLE_NAME IN ('wp_posts','wp_options') GROUP BY TABLE_NAME"],
    'site_health_variables' => ['wp-admin/includes/class-wp-debug-data.php:1830', "SHOW VARIABLES LIKE 'max_allowed_packet'"],
    'site_health_table_status' => ['wp-admin/includes/class-wp-debug-data.php:1923', 'SHOW TABLE STATUS'],
    'repair_check' => ['wp-admin/maint/repair.php:111', 'CHECK TABLE wp_posts'],
    'repair_repair' => ['wp-admin/maint/repair.php:121', 'REPAIR TABLE wp_posts'],
    'repair_analyze' => ['wp-admin/maint/repair.php:134', 'ANALYZE TABLE wp_posts'],
    'repair_optimize' => ['wp-admin/maint/repair.php:143', 'OPTIMIZE TABLE wp_posts'],
    'legacy_duplicate_options' => ['wp-admin/includes/upgrade.php:3736', 'DELETE o1 FROM wp_options AS o1 JOIN wp_options AS o2 USING (option_name) WHERE o2.option_id > o1.option_id'],
    'legacy_charset_conversion' => ['wp-admin/includes/upgrade.php:2826', 'ALTER TABLE wp_posts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'],
    'transient_cleanup' => ['wp-includes/option.php:1645', "DELETE a,b FROM wp_options a,wp_options b WHERE a.option_name LIKE '_transient_%' AND a.option_name NOT LIKE '_transient_timeout_%' AND b.option_name = CONCAT('_transient_timeout_',SUBSTRING(a.option_name,12)) AND b.option_value < 123"],
    'option_upsert' => ['wp-includes/option.php:1142', "INSERT INTO wp_options (option_name,option_value,autoload) VALUES ('probe','value','off') ON DUPLICATE KEY UPDATE option_name=VALUES(option_name),option_value=VALUES(option_value),autoload=VALUES(autoload)"],
    'upgrader_lock' => ['wp-admin/includes/class-wp-upgrader.php:1065', "INSERT IGNORE INTO wp_options (option_name,option_value,autoload) VALUES ('probe.lock','123','off') /* LOCK */"],
];
